/*
 * AboutDialog.java
 *
 * 关于窗口
 *
 * Created on 2010-8-30, 14:37:36
 */
package org.ds.GUI;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 * 关于对话框
 */
public class AboutDialog extends javax.swing.JDialog
{

    /** Creates new form AboutDialog
     * @param parent 父对象
     * @param modal 是否为modal
     */
    public AboutDialog(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
        setLook();  //设置外表
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title1JLabel = new javax.swing.JLabel();
        title2JLabel = new javax.swing.JLabel();
        authorJLabel = new javax.swing.JLabel();
        emailJLabel = new javax.swing.JLabel();
        versionJLabel = new javax.swing.JLabel();
        closeJButton = new javax.swing.JButton();
        emailLinkJLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("关于");

        title1JLabel.setFont(new java.awt.Font("微软雅黑", 0, 36)); // NOI18N
        title1JLabel.setText("桌面搜索");

        title2JLabel.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        title2JLabel.setText("Desktop Search");

        authorJLabel.setText("作者：党凡");

        emailJLabel.setText("Email：");

        versionJLabel.setText("版本：1.0");

        closeJButton.setText("关闭");
        closeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeJButtonActionPerformed(evt);
            }
        });

        emailLinkJLabel.setText("<html><a href=\"mailto:dangf09@gmail.com\">dangf09@gmail.com</a>");
        emailLinkJLabel.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        emailLinkJLabel.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e)
            {
                try
                {
                    Runtime.getRuntime().exec("cmd /c start mailto:dangf09@gmail.com");
                }
                catch (Exception ex)
                {
                    ex.printStackTrace(System.err);
                }
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title1JLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(title2JLabel)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(133, Short.MAX_VALUE)
                .addComponent(closeJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(versionJLabel)
                    .addComponent(authorJLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(emailJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailLinkJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(151, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title1JLabel)
                    .addComponent(title2JLabel))
                .addGap(18, 18, 18)
                .addComponent(versionJLabel)
                .addGap(18, 18, 18)
                .addComponent(authorJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailJLabel)
                    .addComponent(emailLinkJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(closeJButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setLook()
    {
        this.setResizable(false); // 不允许改变尺寸
        this.setLocationRelativeTo(null); // 居中显示
        this.getContentPane().setBackground(new Color(235, 244, 250));
    }

    private void closeJButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_closeJButtonActionPerformed
    {//GEN-HEADEREND:event_closeJButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel authorJLabel;
    private javax.swing.JButton closeJButton;
    private javax.swing.JLabel emailJLabel;
    private javax.swing.JLabel emailLinkJLabel;
    private javax.swing.JLabel title1JLabel;
    private javax.swing.JLabel title2JLabel;
    private javax.swing.JLabel versionJLabel;
    // End of variables declaration//GEN-END:variables
}
