/*
 * ConfigDialog.java
 *
 * 设置窗口
 *
 * Created on 2010-8-30, 15:35:18
 */
package org.ds.GUI;

import com.l2fprod.common.swing.JLinkButton;
import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.util.Enumeration;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.ds.configuration.Configuration;
import org.ds.indexer.FolderTraverser;

/**
 * 设置 对话框
 */
public class ConfigDialog extends javax.swing.JDialog
{

    private Configuration fileConfig;           // 文件类型配置
    private Configuration folderConfig;         // 文件夹配置
    private DefaultListModel folderListModel;   // 文件夹列表模型
    private DefaultListModel fileListModel;     // 文件类型列表模型
    private FolderTraverser traverser;          // 遍历器

    /**
     * 创建新的设置窗口
     * @param parent 父对象
     * @param modal 是否为modal
     * @param traverser 遍历器
     */
    public ConfigDialog(java.awt.Frame parent, boolean modal, FolderTraverser traverser)
    {
        super(parent, modal);
        this.traverser = traverser;
        initComponents();
        setLocationRelativeTo(null);    // 居中
        loadProperties();               // 载入配置文件
        addTimer();                     // 加入计时器，显示索引数量
    }

    //通过配置文件加载默认属性
    private void loadProperties()
    {
        //加载配置文件
        fileConfig = new Configuration("file.config");
        folderConfig = new Configuration("folder.config");

        //设置文件类型
        fileListModel = new DefaultListModel();
        Enumeration files = fileConfig.getProperties();
        while (files.hasMoreElements())
        {
            String key = (String) files.nextElement();
            fileListModel.addElement(key);
        }
        fileJList.setModel(fileListModel);

        //设置文件夹
        folderListModel = new DefaultListModel();
        Enumeration folders = folderConfig.getProperties();
        while (folders.hasMoreElements())
        {
            String key = (String) folders.nextElement();
            folderListModel.addElement(key);
        }
        folderJList.setModel(folderListModel);
    }

    /**
     * 保存配置
     */
    private void saveProperties()
    {
        // 设置文件类型
        for (int i = 0; i < fileListModel.size(); ++i)
        {
            fileConfig.setValue((String) fileListModel.getElementAt(i),
                    "true");
        }

        // 设置文件夹
        for (int i = 0; i < folderListModel.size(); ++i)
        {
            folderConfig.setValue((String) folderListModel.getElementAt(i),
                    "forbidden");
        }

        // 写入配置
        fileConfig.saveFile();
        folderConfig.saveFile();
    }

    // 添加计时器
    private void addTimer()
    {
        Timer timer = new Timer();
        timer.schedule(new TimerTask()
        {

            @Override
            public void run()
            {
                indexCountJLabel.setText(traverser.getIndexCount() + "个");
            }
        }, 0, 200); // 每200ms更新一次
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane = new javax.swing.JSplitPane();
        jTaskPane = new com.l2fprod.common.swing.JTaskPane();
        basicJTaskPaneGroup = new com.l2fprod.common.swing.JTaskPaneGroup();
        advancedJTaskPaneGroup = new com.l2fprod.common.swing.JTaskPaneGroup();
        mainJPanel = new javax.swing.JPanel();
        controlJPanel = new javax.swing.JPanel();
        okJButton = new javax.swing.JButton();
        cancelJButton = new javax.swing.JButton();
        configJPanel = new javax.swing.JPanel();
        folderJPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        folderJList = new javax.swing.JList();
        folderAddJButton = new javax.swing.JButton();
        folderDelJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        fileJPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        fileJList = new javax.swing.JList();
        typeAddJButton = new javax.swing.JButton();
        typeDelJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        extJTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        statusJPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        indexCountJLabel = new javax.swing.JLabel();
        resetJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("设置");
        setResizable(false);

        jTaskPane.setPreferredSize(new java.awt.Dimension(150, 300));

        basicJTaskPaneGroup.setTitle("基本设置");
        basicJTaskPaneGroup.setFont(new java.awt.Font("微软雅黑", 1, 12));
        JLinkButton folderButton = new JLinkButton("文件夹", new ImageIcon(getClass().getResource("/org/ds/GUI/Resources/folder.png")));
        folderButton.addActionListener(new ActionListener()
            {
                public void actionPerformed(ActionEvent e)
                {
                    ((CardLayout)configJPanel.getLayout()).show(configJPanel, "folderCard");
                }
            });
            basicJTaskPaneGroup.add(folderButton);

            JLinkButton fileButton = new JLinkButton("文件类型", new ImageIcon(getClass().getResource("/org/ds/GUI/Resources/file.png")));
            fileButton.addActionListener(new ActionListener()
                {
                    public void actionPerformed(ActionEvent e)
                    {
                        ((CardLayout)configJPanel.getLayout()).show(configJPanel, "fileCard");
                    }
                });
                basicJTaskPaneGroup.add(fileButton);
                jTaskPane.add(basicJTaskPaneGroup);

                advancedJTaskPaneGroup.setTitle("高级设置");
                JLinkButton indexButton = new JLinkButton("索引状态", new ImageIcon(getClass().getResource("/org/ds/GUI/Resources/info.png")));
                indexButton.addActionListener(new ActionListener()
                    {
                        public void actionPerformed(ActionEvent e)
                        {
                            ((CardLayout)configJPanel.getLayout()).show(configJPanel, "statusCard");
                        }
                    });
                    advancedJTaskPaneGroup.add(indexButton);
                    jTaskPane.add(advancedJTaskPaneGroup);

                    jSplitPane.setLeftComponent(jTaskPane);

                    mainJPanel.setLayout(new java.awt.BorderLayout());

                    controlJPanel.setPreferredSize(new java.awt.Dimension(393, 33));
                    controlJPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

                    okJButton.setText("确定");
                    okJButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            okJButtonActionPerformed(evt);
                        }
                    });
                    controlJPanel.add(okJButton);

                    cancelJButton.setText("取消");
                    cancelJButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            cancelJButtonActionPerformed(evt);
                        }
                    });
                    controlJPanel.add(cancelJButton);

                    mainJPanel.add(controlJPanel, java.awt.BorderLayout.SOUTH);

                    configJPanel.setLayout(new java.awt.CardLayout());

                    folderJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("文件夹"));

                    jScrollPane1.setViewportView(folderJList);

                    folderAddJButton.setText("添加");
                    folderAddJButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            folderAddJButtonActionPerformed(evt);
                        }
                    });

                    folderDelJButton.setText("删除");
                    folderDelJButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            folderDelJButtonActionPerformed(evt);
                        }
                    });

                    jLabel1.setText("不进行索引的文件夹：");

                    javax.swing.GroupLayout folderJPanelLayout = new javax.swing.GroupLayout(folderJPanel);
                    folderJPanel.setLayout(folderJPanelLayout);
                    folderJPanelLayout.setHorizontalGroup(
                        folderJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(folderJPanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(folderJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1))
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, folderJPanelLayout.createSequentialGroup()
                            .addContainerGap(251, Short.MAX_VALUE)
                            .addComponent(folderAddJButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(folderDelJButton)
                            .addContainerGap())
                    );
                    folderJPanelLayout.setVerticalGroup(
                        folderJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, folderJPanelLayout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(folderJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(folderDelJButton)
                                .addComponent(folderAddJButton))
                            .addContainerGap())
                    );

                    configJPanel.add(folderJPanel, "folderCard");

                    fileJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("文件类型"));

                    jScrollPane2.setViewportView(fileJList);

                    typeAddJButton.setText("添加");
                    typeAddJButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            typeAddJButtonActionPerformed(evt);
                        }
                    });

                    typeDelJButton.setText("删除");
                    typeDelJButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            typeDelJButtonActionPerformed(evt);
                        }
                    });

                    jLabel2.setText("不索引的文件类型：");

                    jLabel3.setText("扩展名：");

                    javax.swing.GroupLayout fileJPanelLayout = new javax.swing.GroupLayout(fileJPanel);
                    fileJPanel.setLayout(fileJPanelLayout);
                    fileJPanelLayout.setHorizontalGroup(
                        fileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(fileJPanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(fileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fileJPanelLayout.createSequentialGroup()
                            .addContainerGap(131, Short.MAX_VALUE)
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(extJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(typeAddJButton)
                            .addGap(18, 18, 18)
                            .addComponent(typeDelJButton)
                            .addContainerGap())
                    );
                    fileJPanelLayout.setVerticalGroup(
                        fileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fileJPanelLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                            .addGap(10, 10, 10)
                            .addGroup(fileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(typeDelJButton)
                                .addComponent(extJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(typeAddJButton)
                                .addComponent(jLabel3))
                            .addContainerGap())
                    );

                    configJPanel.add(fileJPanel, "fileCard");

                    statusJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("索引状态"));

                    jLabel4.setText("已索引文件：");

                    resetJButton.setText("重置索引");
                    resetJButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            resetJButtonActionPerformed(evt);
                        }
                    });

                    javax.swing.GroupLayout statusJPanelLayout = new javax.swing.GroupLayout(statusJPanel);
                    statusJPanel.setLayout(statusJPanelLayout);
                    statusJPanelLayout.setHorizontalGroup(
                        statusJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(statusJPanelLayout.createSequentialGroup()
                            .addGroup(statusJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(statusJPanelLayout.createSequentialGroup()
                                    .addGap(148, 148, 148)
                                    .addComponent(resetJButton))
                                .addGroup(statusJPanelLayout.createSequentialGroup()
                                    .addGap(35, 35, 35)
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(indexCountJLabel)))
                            .addContainerGap(152, Short.MAX_VALUE))
                    );
                    statusJPanelLayout.setVerticalGroup(
                        statusJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(statusJPanelLayout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addGroup(statusJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(indexCountJLabel))
                            .addGap(72, 72, 72)
                            .addComponent(resetJButton)
                            .addContainerGap(103, Short.MAX_VALUE))
                    );

                    configJPanel.add(statusJPanel, "statusCard");

                    mainJPanel.add(configJPanel, java.awt.BorderLayout.CENTER);

                    jSplitPane.setRightComponent(mainJPanel);

                    getContentPane().add(jSplitPane, java.awt.BorderLayout.CENTER);

                    pack();
                }// </editor-fold>//GEN-END:initComponents

    // 取消按钮，隐藏对话框
    private void cancelJButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelJButtonActionPerformed
    {//GEN-HEADEREND:event_cancelJButtonActionPerformed
        setVisible(false);
    }//GEN-LAST:event_cancelJButtonActionPerformed

    // 确定按钮，保存配置，并隐藏对话框
    private void okJButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_okJButtonActionPerformed
    {//GEN-HEADEREND:event_okJButtonActionPerformed
        saveProperties();
        setVisible(false);
    }//GEN-LAST:event_okJButtonActionPerformed

    // 删除按钮，在文件夹黑名单列表中删除一项
    private void folderDelJButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_folderDelJButtonActionPerformed
    {//GEN-HEADEREND:event_folderDelJButtonActionPerformed
        int index = folderJList.getSelectedIndex();
        if (index != -1)    //如果有选项被选中
        {
            folderListModel.remove(index);
        }
    }//GEN-LAST:event_folderDelJButtonActionPerformed

    // 添加按钮，在黑名单列表中增加一项
    private void folderAddJButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_folderAddJButtonActionPerformed
    {//GEN-HEADEREND:event_folderAddJButtonActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);  //设置仅能选中目录
        int returnValue = fileChooser.showDialog(this, "确定");           //显示选择对话框
        if (returnValue == JFileChooser.APPROVE_OPTION)                   //如果选中了文件夹
        {
            folderListModel.addElement(fileChooser.getSelectedFile().toString());
        }
    }//GEN-LAST:event_folderAddJButtonActionPerformed

    // 文件类型添加按钮
    private void typeAddJButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_typeAddJButtonActionPerformed
    {//GEN-HEADEREND:event_typeAddJButtonActionPerformed
        String ext = extJTextField.getText();
        if (!ext.equals(""))    // 不空，则添加
        {
            fileListModel.addElement(ext);
        }
    }//GEN-LAST:event_typeAddJButtonActionPerformed

    // 文件类型删除按钮
    private void typeDelJButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_typeDelJButtonActionPerformed
    {//GEN-HEADEREND:event_typeDelJButtonActionPerformed
        int index = fileJList.getSelectedIndex();
        if (index != -1)    //如果有选项被选中
        {
            fileListModel.remove(index);
        }
    }//GEN-LAST:event_typeDelJButtonActionPerformed

    // 清空索引按钮
    private void resetJButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_resetJButtonActionPerformed
    {//GEN-HEADEREND:event_resetJButtonActionPerformed
        if (JOptionPane.showConfirmDialog(this, "真的要清空所有的索引吗？", "清空索引",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE,
                new ImageIcon(getClass().getResource(
                "/org/ds/GUI/Resources/question.png"))) == JOptionPane.YES_OPTION)
        {
            try
            {
                new File("reset").createNewFile();  // 创建reset文件
            }
            catch (Exception e)
            {
            }
            JOptionPane.showMessageDialog(this, "索引将在重新运行本程序时清空！");
        }
    }//GEN-LAST:event_resetJButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.l2fprod.common.swing.JTaskPaneGroup advancedJTaskPaneGroup;
    private com.l2fprod.common.swing.JTaskPaneGroup basicJTaskPaneGroup;
    private javax.swing.JButton cancelJButton;
    private javax.swing.JPanel configJPanel;
    private javax.swing.JPanel controlJPanel;
    private javax.swing.JTextField extJTextField;
    private javax.swing.JList fileJList;
    private javax.swing.JPanel fileJPanel;
    private javax.swing.JButton folderAddJButton;
    private javax.swing.JButton folderDelJButton;
    private javax.swing.JList folderJList;
    private javax.swing.JPanel folderJPanel;
    private javax.swing.JLabel indexCountJLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane;
    private com.l2fprod.common.swing.JTaskPane jTaskPane;
    private javax.swing.JPanel mainJPanel;
    private javax.swing.JButton okJButton;
    private javax.swing.JButton resetJButton;
    private javax.swing.JPanel statusJPanel;
    private javax.swing.JButton typeAddJButton;
    private javax.swing.JButton typeDelJButton;
    // End of variables declaration//GEN-END:variables
}
